import type { NextPage } from "next";
import Head from "next/head";
import { _TodoService } from "@services";
import styles from "styles/Home.module.scss";
import { Archive, Doing, Done, Todo } from "@components";

const Home: NextPage = () => {
 

  return (
    <div className=" pt-28">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={`${styles.todoTitle} w-full text-center pb-10 `}>
        TODO LIST
      </h1>

      <div className=" 
       flex flex-row items-start justify-between
        px-5 space-x-10">
    <Todo/>
    <Done/>
    <Doing/>
    <Archive/>
      </div>
    </div>
  );
};

export default Home;
