import type { NextPage } from 'next'
import Head from 'next/head'
import { _TodoService } from '@services'



const Home: NextPage = () => {
  const dodo=()=>{
    _TodoService.Index().subscribe({
      next:res=>console.log(res.data),
      error:err=>console.log(err.response)
    })
  }

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 onClick={()=>dodo()} className="text-3xl font-bold underline">
      Hello world!
    </h1>

    </div>
  )
}

export default Home
